language: python

python:
  - '3.7'
  - '3.8'

before_install:
- sudo find /usr -name '*.pyc' -delete
- bash install_common_deps.sh
- pip install -r requirements.txt 
- pip install -r tests/requirements.txt

install:
- python setup.py install

script:
- pytest --cov-append --cov=./reneu ./tests --verbose

after_success:
- coveralls
