# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:

# References
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# https://github.com/MicrosoftDocs/pipelines-anaconda/blob/master/azure-pipelines.yml
# https://github.com/matplotlib/mplcairo/blob/master/azure-pipelines.yml

strategy:
  matrix:
    Linux_py37:
      vmImage: 'ubuntu-16.04'
      pythonVersion: '3.7'
    Linux_py38:
      vmImage: 'ubuntu-16.04'
      pythonVersion: '3.8'
  pool:
    vmImage: '$(vmImage)'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: conda env create --quiet --file environment.yml
    displayName: Create Anaconda environment

  - bash: |
      sudo apt update &&
      sudo apt install libboost-dev
      source activate reneu
      python setup.py develop
      pip install pytest pytest-azurepipelines
      pytest tests
      sudo PY_VERS="$PYTHONVERSION" tools/build-manylinux-wheel.sh
    displayName: pytest
