# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package build and push

on: [push, pull_request] 

jobs:
  build:

    -runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        bash install_common_deps.sh
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt

    - name: Python wheels manylinux build
      uses: RalfG/python-wheels-manylinux-build@v0.4.2
      with:
        python-versions: 'cp39-cp39m'
        build-requirements: 'cython numpy'
        system-packages: 'cmake lrzip-devel zlib-devel libboost-dev'
        package-path: ''
        pip-wheel-args: '-w ./dist --no-deps'
    
    - name: Test with pytest
      run: |
        pip install pytest
        pytest ./tests

    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload ./dist/*-manylinux*.whl
